headers := PrintFunks.h
funcs := MatrixPrintFunc.c PrintArrayBackwards.c PrintSquareFunK.c PrintTriangles.c Snail.c
main := Main.c
all := $(headers) $(funcs) $(main)
bin := Arrays.exe

$(bin): $(all)
		gcc $(all) -o $(bin)